# Generated by Django 6.1.1 on 2026-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='musicbrainzartisttag',
            index=models.Index(fields=['id'], name='artist_tag_track_id_idx'),
        ),
        migrations.AddIndex(
            model_name='spotifytrack',
            index=models.Index(fields=['track_id'], name='track_id_idx'),
        ),
        migrations.AddIndex(
            model_name='spotifytrackembedding',
            index=models.Index(fields=['track_id'], name='embedding_track_id_idx'),
        ),
    ]
